import type { Metadata } from "next";
import { Geist, Geist_Mono, Macondo } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/ui/navigation/footer";
import MainNavigation from "@/components/ui/navigation/main-navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const comicFont = localFont({
  src: "./fonts/Comic_Neue/ComicNeue-Regular.ttf",
});

const macondoFont = localFont({
  src: "./fonts/Macondo-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${comicFont.className} antialiased flex flex-col justify-between min-h-screen `}
      >
        <MainNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
